services:
  api-server:
    build: .
    tty: true
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - type: bind
        source: .
        target: /api-server
    depends_on:
      - db-server
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
  db-server:
    container_name: db-server
    image: mysql:5.7.29
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
