name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #   node-version: [19.x]
    steps:
      # - uses: actions/checkout@v4
      # - name: Build the Docker image
      #   run: docker build . --file packages/server/Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/checkout@v3

    - name: Setup Node
    uses: actions/setup-node@v3
    with:
        node-version: "19.x"
    uses: actions/cache@v2
    with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

          - run: npm ci
          - run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install SSH Key for Deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         key: ${{ secrets.SK }}
  #         host: ${{secrets.SSH_HOST}}
  #         username: ${{secrets.SSH_USERNAME}}
  #         port: ${{secrets.SSH_PORT}}
  #         script: |
  #           git pull origin main
